const mongoose = require('mongoose');
const { Schema } = mongoose;

const jobSchema = new Schema({
    jobId: {type: String, default: ''},
    vessel: {type: Schema.Types.ObjectId, ref: 'vessels'},
    jobTrackers: [{type: Schema.Types.ObjectId, ref: 'jobTrackers'}],
    paymentTrackers: [{type: Schema.Types.ObjectId, ref: 'paymentTrackers'}],
    vesselLoadingLocation: {type: Schema.Types.ObjectId, ref: 'vesselLoadingLocations'},
    vesselLoadingLocationObj: {type: Schema.Types.ObjectId, ref: 'vesselLoadingLocations'},
    otherVesselLoadingLocation: {type: String, default: ''},
    user: {type: Schema.Types.ObjectId, ref: 'users'},
    index: {type: String, default: ''},
    jobItems: [{type: Schema.Types.ObjectId, ref: 'jobItems'}],
    jobOfflandItems: [{type: Schema.Types.ObjectId, ref: 'jobOfflandItems'}],
    careOffParties: [{type: Schema.Types.ObjectId, ref: 'careOffParties'}],
    jobBookingDateTime: {type: Date, default: new Date()},
    vesselArrivalDateTime: {type: Date, default: null},
    remarks: {type: String, default: ''},
    vesselLoadingDateTime: {type: Date, default: null},
    psaBerthingDateTime: {type: Date, default: null},
    psaUnberthingDateTime: {type: Date, default: null},
    googleCalendarId: {type: String, default: ''},
    isCancelled: {type: String, default: 'Nil'},
    cancellationRemarks: {type: String, default: ''},
    isArchived: {type: Boolean, default: false},
    createDSA: {type: Boolean, default: false},
    pickup: {type: Boolean, default: false},
    pickupDetails: [{type: Schema.Types.ObjectId, ref: 'pickupDetails'}],
    vesselLighterName: {type: String, default: ''},
    vesselLighterLocation: {type: String, default: ''},
    vesselLighterRemarks: {type: String, default: ''},
    jobTrip: {type: Schema.Types.ObjectId, ref: 'jobTrips'},
    psaQuayCraneSequences: [{type: Schema.Types.ObjectId, ref: 'psaQuayCraneSequences'}],
    jobTrackerRemarks: {type: String, default: ''},
    psaVoyageNumberIn: {type: String, default: ""},
    psaVoyageNumberOut: {type: String, default: ""},
    psaBerf: {type: String, default: ""},
    telegramMessageId: {type: String, default: ""},
    jobPrices:[{type: Schema.Types.ObjectId, ref: 'jobPrices'}],
});

module.exports = mongoose.model('jobs', jobSchema);
